name: release version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          version-minor: true

          maven-args: "-B -DskipITs -Dmaven.deploy.skip=true"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}

          docker-registry-id: ossrh
          docker-registry-username: ${{ secrets.OSSRH_USERNAME }}
          docker-registry-password: ${{ secrets.OSSRH_PASSWORD }}
